name: Build and Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-unit:

    runs-on: ubuntu-latest

    steps:
    - name: chekout the code
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: install npm dependencies
      run: npm install
    - name: execute unit tests
      run: npm run test:unit
    - name: display username
      run: echo 'Tuncher-Ismail'


  build-and-test-ui:
    needs: build-and-test-unit

    runs-on: ubuntu-latest

    steps:
    - name: chekout the code
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: install npm dependencies
      run: npm install
    - name: npx playwright install
      run: npx playwright install
    - name: start the application
      run: npm start &
    - name: execute ui tests
      run: npm run test:ui


  deploy:
    needs: build-and-test-ui
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_KEY }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          
